### PR TITLE
Added basic hero section and navbar on the landing page.

### PR DESCRIPTION
**Pull request by srijan-paul**
Replaced the code for the taquito template with a hero section.
image

It doesn't do anything at the moment but I thought we might want to see if we agree on the architecture practices etc.

Note that the code for the template is still available under `components/Template.tsx`. All we have to do to use that is:
```tsx
function App() {
	return (
		<div className="App">
			// replace the line below with: <Template />
			<Home />
		</div>
	);
}
```

Next up, we might want to have a `connect wallet` button that connects the wallet to the app.

### CODE REVIEW

**Review by ahv15 — COMMENTED** [review]
Overall, it looks good. So the next step would be to integrate the existing ConnectWalletButton from the template into the homepage and add a breeding section in the navbar to temporarily test our smart contracts. I'll try and setup the project and work on this tomorrow. @Mihir018 would you be able to give a functional review before I set the project up?

**Review by ahv15 — APPROVED** [review]
Set everything up and tested it out works fine.

**Comment by srijan-paul** [comment]
> Set everything up and tested it out works fine.

Ah, I realized it might be getting tedious to test stuff everytime like this.
I'll set up some simple unit tests on CI tomorrow.

**Comment by Mihir018** [comment]
@ahv15 sure, will do it..

**Pull request merged**
