### PR TITLE
BitHound Contracts

### PR DESCRIPTION
**Pull request by Mihir018**
main BitHounds smart-contract

### CODE REVIEW

**Comment by Mihir018** [comment]
ezgif com-gif-maker

Its been tested on online IDE, will deploy it after testing it locally and verifying all test cases.

**Comment by srijan-paul** [comment]
Thanks! We could deploy it after a quick meet. What do you think?

**Review by ahv15 — COMMENTED** [review]
I'll review this once you test this locally.

**Comment by Mihir018** [comment]
> I'll review this once you test this locally.

sounds good

**Comment by srijan-paul** [comment]
@Mihir018 There is still no entry point for creating a hound. We'll need one if we have to call this from the web client. Could you add a `makeHound` entry point? While we're on that, I think we can do without the `lend` and `checkAvailable` for now. What do you think?

**Comment by Mihir018** [comment]
> @Mihir018 There is still no entry point for creating a hound. We'll need one if we have to call this from the web client. Could you add a `makeHound` entry point? While we're on that, I think we can do without the `lend` and `checkAvailable` for now. What do you think?

I am working on it, what I am thinking is to make that functionality work from `create` entry point itself, what I am thinking is to create a `createHound` sub-entry point which will be called in `create` entry point, like we have done in the `breed` entry point 

create

Here is the  `createHound` code -

`def createHound(self, houndId, price, owner):
        return sp.record(houndId = houndId, owner = owner, price = sp.utils.nat_to_tez(price), isNew = True, auction = sp.timestamp(0), breeding = sp.timestamp(0), generation = 0, borrowPrice = sp.mutez(0))
` 

let me know if it makes sense, or do comment if you have any suggestion or questions .

**Comment by srijan-paul** [comment]
By the looks of it, `createHound` is a regular smartpy function and not an actual entry point right?
Do you mean that the `create` entry point calls `createHound`? That sounds reasonable to me.

If you could commit that I think we'd be able to merge this.

**Comment by Mihir018** [comment]
yaa right `create` is  making a entry point call to `createHound` 

I made changes in the code, I will resolve a `type-error` that is popping up and will commit it

**Review by srijan-paul — APPROVED** [review]
looks good! I'll wait for @ahv15 since he is the one who's going to be calling the entry points.

**Review by ahv15 — APPROVED** [review]

**Pull request merged**
